# This file is part of rss-reader
# https://github.com/scorphus/rss-reader

# Licensed under the BSD-3-Clause license:
# https://opensource.org/licenses/BSD-3-Clause
# Copyright (c) 2023, Pablo S. Blum de Aguiar <scorphus@gmail.com>

[tool.black]
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.tox
    | dist
  )/
)
'''
line-length = 99

[[tool.mypy.overrides]]
module = ["logtail", "feedparser"]
ignore_missing_imports = true
